### ISSUE TITLE
TypeError: Property typeName of TSTypeReference expected node to be of a type ["TSEntityName"] but instead got "MemberExpression"

### ISSUE THREAD

**Issue by hammadj** [Kiikurage/babel-plugin-flow-to-typescript#23]
The file in question:
```js
// @flow
import { Alert } from 'react-native';
import idx from 'idx';
import * as appActions from '../App/actions';
import displayError, { type Buttons } from '../utils/displayError';

export const mapDispatchToPropsForRedirectToAppRoot = (dispatch: Dispatch) => ({
  redirectAppRoot: () => dispatch(appActions.redirectAppRoot()),
});

export const redirectToAppRootWithAlert = (
  title: string,
  message: string,
  redirectAppRoot: () => void,
) => {
  Alert.alert(title, message, [
    {
      text: 'Ok',
      onPress: () => {
        redirectAppRoot();
      },
    },
  ]);
};

export const isViewerProfileValid = (viewer: ?Viewer) => {
  const emailVerified = idx(viewer, _ => _.emailVerified);
  const mobileVerified = idx(viewer, _ => _.mobileVerified);

  return Boolean(emailVerified && mobileVerified);
};

export function displayAuthError(
  e: Error | string,
  errorMessage?: ?string,
  buttons?: Buttons,
) {
  return displayError(e, errorMessage, buttons, {
    screenArea: 'Auth',
  });
}
```

Full error:

```
TypeError: Property typeName of TSTypeReference expected node to be of a type ["TSEntityName"] but instead got "MemberExpression"
    at Object.validate (/Users/hammadjutt/.nvm/versions/node/v8.11.2/lib/node_modules/@babel/core/node_modules/@babel/types/lib/definitions/utils.js:128:13)
    at Object.validate (/Users/hammadjutt/.nvm/versions/node/v8.11.2/lib/node_modules/@babel/core/node_modules/@babel/types/lib/validators/validate.js:17:9)
    at NodePath._replaceWith (/Users/hammadjutt/.nvm/versions/node/v8.11.2/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/replacement.js:194:9)
    at NodePath.replaceWith (/Users/hammadjutt/.nvm/versions/node/v8.11.2/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/replacement.js:178:8)
    at Object.ReferencedIdentifier (/Users/hammadjutt/Dev/Upwork/homepass-nxt/node_modules/@babel/helper-module-transforms/lib/rewrite-live-references.js:204:14)
    at Object.newFn (/Users/hammadjutt/.nvm/versions/node/v8.11.2/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/visitors.js:230:17)
    at NodePath._call (/Users/hammadjutt/.nvm/versions/node/v8.11.2/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/hammadjutt/.nvm/versions/node/v8.11.2/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/hammadjutt/.nvm/versions/node/v8.11.2/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/Users/hammadjutt/.nvm/versions/node/v8.11.2/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:118:16)
```

**Comment by steelbrain** [comment]
Here's my fix for it https://github.com/steelbrain/babel-plugin-flow-to-typescript/commit/73ee8b914b1390d2358cdf3a9e79301cdde46504

Not ideal, but works 🤷‍♂️
